# Generated by Django 4.1 on 2022-09-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('django', 'django'), ('python', 'python'), ('html', 'html'), ('java', 'java'), ('css', 'css'), ('bootstrap', 'bootstrap'), ('annonce', 'annonce')], default='django', max_length=100),
        ),
    ]
