# Generated by Django 4.1 on 2022-09-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=1000)),
            ],
            options={
                'db_table': 'email',
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=100),
        ),
    ]
